import './globals.css';
import { SITE_CONFIG } from '../../site.config';
import { Head } from 'next/document';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang={SITE_CONFIG.meta.lang}>
      <Head>
        <></>
      </Head>
      <body>{children}</body>
    </html>
  );
}
