import "./globals.css";

/**
 * layout.tsx
 * shared UI in every Components
 * similar with _app, _document
 */

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
